#!/usr/bin/env python3
# SHIM: Redirects to PIA Architecture Layer
# Generated by: apply_shims_v1.py
# Date: 2026-02-03

import sys
import os
import importlib.util

# 1. Resolve PIA Root
PIA_ROOT = os.environ.get("PIA_ROOT", "/root/pib/pia")
if not os.path.exists(PIA_ROOT):
    print(f"CRITICAL: PIA_ROOT not found at {PIA_ROOT}", file=sys.stderr)
    sys.exit(1)

# 2. Map Tool to PIA Path
TOOL_MAP = {
    "infercell_manager.py": "core/context",
    "infercell_activator.py": "core/context",
    "falkordb_advanced.py": "core/memory",
    "falkordb_api.py": "core/memory",
    "falkordb_bus_events.py": "core/memory",
    "falkordb_dialogos.py": "core/memory",
    "falkordb_health.py": "core/memory",
    "falkordb_lineage.py": "core/memory",
    "falkordb_lineage_walker.py": "core/memory",
    "falkordb_migrate.py": "core/memory",
    "falkordb_omega.py": "core/memory",
    "falkordb_pbresume_integration.py": "core/memory",
    "falkordb_pool.py": "core/memory",
    "falkordb_protocol.py": "core/memory",
    "falkordb_schema.py": "core/memory",
    "falkordb_tasks.py": "core/memory",
    "a2a_dispatcher.py": "core/dispatch",
    "semops_actions.py": "specs/registry",
    "semops_invoke_responder.py": "specs/registry",
    "semops_lexer.py": "specs/registry",
}

# 3. Import and Execute
current_file = os.path.basename(__file__)
if current_file not in TOOL_MAP:
    print(f"CRITICAL: Unknown shim target {current_file}", file=sys.stderr)
    sys.exit(1)

rel_path = TOOL_MAP[current_file]
target_path = os.path.join(PIA_ROOT, rel_path, current_file)

if not os.path.exists(target_path):
    print(f"CRITICAL: Target not found {target_path}", file=sys.stderr)
    sys.exit(1)

spec = importlib.util.spec_from_file_location("main_module", target_path)
module = importlib.util.module_from_spec(spec)
# CRITICAL FIX: dataclasses requires the module to be in sys.modules with a valid __dict__
sys.modules["main_module"] = module 
sys.modules["__main__"] = module
spec.loader.exec_module(module)
