#!/usr/bin/env bash
#
# setup_https.sh - Automated HTTPS setup for Pluribus Dashboard
#
# Uses Let's Encrypt free certificates via Caddy (recommended) or Nginx+Certbot.
#
# Usage:
#   ./setup_https.sh                    # Interactive mode
#   ./setup_https.sh --domain example.com --method caddy
#   ./setup_https.sh --domain example.com --method nginx
#   ./setup_https.sh --check            # Check current SSL status
#
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLURIBUS_ROOT="$(dirname "$SCRIPT_DIR")"

# Default values
DOMAIN=""
METHOD=""
DASHBOARD_PORT="${DASHBOARD_PORT:-5173}"
EMAIL="${LETSENCRYPT_EMAIL:-}"

log_info() { echo -e "${CYAN}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_domain_dns() {
    local domain="$1"
    local server_ip
    server_ip=$(curl -s ifconfig.me || curl -s icanhazip.com)

    log_info "Checking DNS for $domain..."

    local resolved_ip
    resolved_ip=$(dig +short "$domain" | head -1)

    if [[ -z "$resolved_ip" ]]; then
        log_error "Domain $domain does not resolve to any IP"
        log_warn "Please configure DNS A record pointing to: $server_ip"
        return 1
    fi

    if [[ "$resolved_ip" != "$server_ip" ]]; then
        log_warn "Domain resolves to $resolved_ip but server IP is $server_ip"
        read -p "Continue anyway? (y/N): " confirm
        [[ "$confirm" =~ ^[Yy]$ ]] || exit 1
    else
        log_success "DNS correctly points to this server ($server_ip)"
    fi
}

check_ports() {
    log_info "Checking required ports..."

    # Check port 80
    if ss -tlnp | grep -q ':80 '; then
        local service
        service=$(ss -tlnp | grep ':80 ' | awk '{print $NF}')
        log_warn "Port 80 is in use by: $service"
    else
        log_success "Port 80 is available"
    fi

    # Check port 443
    if ss -tlnp | grep -q ':443 '; then
        local service
        service=$(ss -tlnp | grep ':443 ' | awk '{print $NF}')
        log_warn "Port 443 is in use by: $service"
    else
        log_success "Port 443 is available"
    fi
}

install_caddy() {
    log_info "Installing Caddy..."

    if command -v caddy &>/dev/null; then
        log_success "Caddy already installed: $(caddy version)"
        return 0
    fi

    apt-get update
    apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl

    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | \
        gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | \
        tee /etc/apt/sources.list.d/caddy-stable.list

    apt-get update
    apt-get install -y caddy

    log_success "Caddy installed: $(caddy version)"
}

configure_caddy() {
    local domain="$1"

    log_info "Configuring Caddy for $domain..."

    # Backup existing config
    if [[ -f /etc/caddy/Caddyfile ]]; then
        cp /etc/caddy/Caddyfile "/etc/caddy/Caddyfile.backup.$(date +%Y%m%d%H%M%S)"
    fi

    cat > /etc/caddy/Caddyfile <<EOF
# Pluribus Dashboard HTTPS Configuration
# Generated by setup_https.sh on $(date)

$domain {
    # Reverse proxy to Vite dev server
    reverse_proxy localhost:$DASHBOARD_PORT

    # WebSocket support for HMR (Hot Module Replacement)
    @websockets {
        header Connection *Upgrade*
        header Upgrade websocket
    }
    reverse_proxy @websockets localhost:$DASHBOARD_PORT

    # Logging
    log {
        output file /var/log/caddy/pluribus.log
        format json
    }

    # Security headers
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
    }
}

# Redirect www to non-www (optional)
www.$domain {
    redir https://$domain{uri} permanent
}
EOF

    mkdir -p /var/log/caddy

    # Validate config
    if caddy validate --config /etc/caddy/Caddyfile; then
        log_success "Caddy configuration valid"
    else
        log_error "Caddy configuration invalid"
        exit 1
    fi

    # Restart Caddy
    systemctl enable caddy
    systemctl restart caddy

    log_success "Caddy configured and started"
}

install_nginx_certbot() {
    log_info "Installing Nginx and Certbot..."

    apt-get update
    apt-get install -y nginx certbot python3-certbot-nginx

    log_success "Nginx and Certbot installed"
}

configure_nginx() {
    local domain="$1"

    log_info "Configuring Nginx for $domain..."

    # Create nginx config
    cat > /etc/nginx/sites-available/pluribus <<EOF
# Pluribus Dashboard Configuration
# Generated by setup_https.sh on $(date)

server {
    listen 80;
    listen [::]:80;
    server_name $domain www.$domain;

    location / {
        proxy_pass http://127.0.0.1:$DASHBOARD_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket timeout for HMR
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
EOF

    # Enable site
    ln -sf /etc/nginx/sites-available/pluribus /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default

    # Test and reload
    nginx -t
    systemctl enable nginx
    systemctl reload nginx

    log_success "Nginx configured"
}

obtain_certificate_nginx() {
    local domain="$1"
    local email_arg=""

    if [[ -n "$EMAIL" ]]; then
        email_arg="--email $EMAIL"
    else
        email_arg="--register-unsafely-without-email"
    fi

    log_info "Obtaining Let's Encrypt certificate for $domain..."

    certbot --nginx \
        -d "$domain" \
        --non-interactive \
        --agree-tos \
        $email_arg \
        --redirect

    log_success "Certificate obtained and Nginx configured for HTTPS"

    # Verify renewal
    log_info "Testing certificate renewal..."
    certbot renew --dry-run
    log_success "Auto-renewal configured"
}

check_ssl_status() {
    log_info "Checking SSL status..."

    local server_ip
    server_ip=$(curl -s ifconfig.me 2>/dev/null || echo "unknown")
    echo "Server IP: $server_ip"
    echo

    # Check Caddy
    if systemctl is-active --quiet caddy 2>/dev/null; then
        log_success "Caddy is running"
        caddy version
        echo "Caddyfile:"
        head -20 /etc/caddy/Caddyfile 2>/dev/null || echo "  (not found)"
    else
        log_warn "Caddy not running"
    fi
    echo

    # Check Nginx
    if systemctl is-active --quiet nginx 2>/dev/null; then
        log_success "Nginx is running"
        nginx -v 2>&1
        echo "Sites enabled:"
        ls -la /etc/nginx/sites-enabled/ 2>/dev/null || echo "  (none)"
    else
        log_warn "Nginx not running"
    fi
    echo

    # Check Certbot certificates
    if command -v certbot &>/dev/null; then
        log_info "Let's Encrypt certificates:"
        certbot certificates 2>/dev/null || echo "  (none found)"
    fi
    echo

    # Check port listeners
    log_info "Port listeners:"
    ss -tlnp | grep -E ':80|:443' || echo "  No services on 80/443"
}

show_usage() {
    cat <<EOF
Pluribus HTTPS Setup Script

Usage: $0 [OPTIONS]

Options:
    --domain DOMAIN     Domain name for the certificate (required for setup)
    --method METHOD     Setup method: 'caddy' (recommended) or 'nginx'
    --email EMAIL       Email for Let's Encrypt notifications
    --port PORT         Dashboard port (default: 5173)
    --check             Check current SSL/HTTPS status
    --help              Show this help message

Examples:
    # Interactive setup
    sudo $0

    # Automated setup with Caddy
    sudo $0 --domain dashboard.example.com --method caddy

    # Automated setup with Nginx + Certbot
    sudo $0 --domain dashboard.example.com --method nginx --email admin@example.com

    # Check current status
    sudo $0 --check

Notes:
    - Requires a domain name (Let's Encrypt cannot issue certs for IP addresses)
    - DNS must point to this server before running
    - Ports 80 and 443 must be accessible
    - Caddy handles certificates automatically
    - Nginx uses Certbot for certificate management

Free Domain Options:
    - DuckDNS: https://www.duckdns.org (free subdomain)
    - sslip.io: Use IP in domain (e.g., 69-169-104-17.sslip.io)
EOF
}

interactive_setup() {
    echo
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║       Pluribus Dashboard HTTPS Setup (Let's Encrypt)       ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo

    local server_ip
    server_ip=$(curl -s ifconfig.me 2>/dev/null || echo "unknown")
    log_info "Server IP: $server_ip"
    echo

    # Get domain
    if [[ -z "$DOMAIN" ]]; then
        echo "Enter your domain name (e.g., dashboard.example.com)"
        echo "  Tip: Use ${server_ip//./-}.sslip.io for quick testing"
        read -p "Domain: " DOMAIN
    fi

    if [[ -z "$DOMAIN" ]]; then
        log_error "Domain is required"
        exit 1
    fi

    # Get method
    if [[ -z "$METHOD" ]]; then
        echo
        echo "Select setup method:"
        echo "  1) Caddy (Recommended - automatic HTTPS)"
        echo "  2) Nginx + Certbot (Traditional)"
        read -p "Choice [1]: " choice
        case "${choice:-1}" in
            1) METHOD="caddy" ;;
            2) METHOD="nginx" ;;
            *) METHOD="caddy" ;;
        esac
    fi

    echo
    log_info "Setting up HTTPS for $DOMAIN using $METHOD"
    echo

    # Run setup
    check_domain_dns "$DOMAIN"
    check_ports

    case "$METHOD" in
        caddy)
            install_caddy
            configure_caddy "$DOMAIN"
            ;;
        nginx)
            install_nginx_certbot
            configure_nginx "$DOMAIN"
            obtain_certificate_nginx "$DOMAIN"
            ;;
        *)
            log_error "Unknown method: $METHOD"
            exit 1
            ;;
    esac

    echo
    log_success "HTTPS setup complete!"
    echo
    echo "Your dashboard is now available at:"
    echo "  https://$DOMAIN"
    echo
    echo "WebGPU/WebLLM should now work in the browser!"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --method)
            METHOD="$2"
            shift 2
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --port)
            DASHBOARD_PORT="$2"
            shift 2
            ;;
        --check)
            check_ssl_status
            exit 0
            ;;
        --help|-h)
            show_usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

# Main
check_root
interactive_setup
